" enable syntax highlighting
syntax on

" enable indentation
filetype plugin indent on
set autoindent
set expandtab
set shiftwidth=2
set softtabstop=2

" automatically wrap left and right
set whichwrap+=<,>,h,l,[,]

" solarized
" if terminal is not set to solarized
" let g:solarized_termcolors=256
" set solarized colorscheme
"set background=dark
"colorscheme solarized

" molokai
" let g:molokai_original = 1
" let g:rehash256 = 1
set background=dark
colorscheme molokai
